### ISSUE TITLE
Adaptive time-stepping

### ISSUE THREAD

**Issue by mpaesold** [pou036/redback#1]
Currently, Redback is only running with a fixed time step. Andrew seems to know a solution for this. 

Andy's solution to check convergence at every Gauss point seems to be preferable. The input file drained_triaxial_compression_CC.i is the most sensitive example for the time being. 

*** Andy's email from the Moose user group ***

Hi Thomas,
 
Sorry for my slow reply – i was on holidays until today.
 
Have a look at src/materials/FiniteStrainMultiPlasticity::plasticStep .  There i subdivide the applied strain increment into smaller steps if the returnmap fails.  This is gauss-point-by-gauss-point “timestep” cutting.  At present it is not possible in MOOSE to cut the real timestep for the whole mesh, unfortunately.  This is currently being worked upon, eg, see
 
https://github.com/idaholab/moose/issues/3789
 
a

**Comment by pou036** [comment]
We're using custom timestep_functions, see Oka for example
